// <auto-generated />
using System;
using MercenariesAndBeasts.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MercenariesAndBeasts.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251129114904_LocationAiGenerationCode1Fix")]
    partial class LocationAiGenerationCode1Fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Dungeon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UnlockOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.DungeonStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyRating")
                        .HasColumnType("integer");

                    b.Property<Guid>("DungeonId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("MonsterTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecommendedLevel")
                        .HasColumnType("integer");

                    b.Property<int>("StageIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StageType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DungeonId");

                    b.HasIndex("MonsterTemplateId");

                    b.ToTable("DungeonStages");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.ExpeditionStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("EnemyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FixedLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("LocationId");

                    b.ToTable("ExpeditionStages");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Items.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<int>("BaseQuality")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Items.PlayerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrefixCode")
                        .HasColumnType("text");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<string>("SuffixCode")
                        .HasColumnType("text");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UnlockOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Players.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveMercenaryTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveMonsterTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.DungeonAchievementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DungeonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DungeonId");

                    b.ToTable("DungeonAchievements");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.ExpeditionAchievementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("ExpeditionAchievements");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerDungeonAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerDungeonAchievements");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerDungeonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DungeonId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxStageReached")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DungeonId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerDungeonProgresses");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerExpeditionAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerExpeditionAchievements");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerExpeditionProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxStageReached")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerExpeditionProgresses");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.MercenaryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MercenaryTemplates");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.MonsterTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Element")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MonsterTemplates");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.PlayerMercenary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PlayerMercenaries");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.PlayerMonster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PlayerMonsters");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Infrastructure.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MercenariesAndBeasts.Items.ItemEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("ItemTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetStat")
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("ItemEffect");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.DungeonStage", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Dungeon", "Dungeon")
                        .WithMany("Stages")
                        .HasForeignKey("DungeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Units.MonsterTemplate", "MonsterTemplate")
                        .WithMany()
                        .HasForeignKey("MonsterTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dungeon");

                    b.Navigation("MonsterTemplate");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.ExpeditionStage", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Units.MercenaryTemplate", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Location", "Location")
                        .WithMany("Stages")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Items.ItemTemplate", b =>
                {
                    b.OwnsOne("MercenariesAndBeasts.Domain.Combat.StatBlock", "BaseStats", b1 =>
                        {
                            b1.Property<Guid>("ItemTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer");

                            b1.Property<double>("CritChance")
                                .HasColumnType("double precision");

                            b1.Property<double>("CritMultiplier")
                                .HasColumnType("double precision");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("ElementalDamageBonus")
                                .HasColumnType("double precision");

                            b1.Property<double>("ElementalResistance")
                                .HasColumnType("double precision");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.HasKey("ItemTemplateId");

                            b1.ToTable("ItemTemplates");

                            b1.WithOwner()
                                .HasForeignKey("ItemTemplateId");
                        });

                    b.Navigation("BaseStats")
                        .IsRequired();
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Items.PlayerItem", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Players.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Items.ItemTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MercenariesAndBeasts.Domain.Combat.StatBlock", "BonusStats", b1 =>
                        {
                            b1.Property<Guid>("PlayerItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer");

                            b1.Property<double>("CritChance")
                                .HasColumnType("double precision");

                            b1.Property<double>("CritMultiplier")
                                .HasColumnType("double precision");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("ElementalDamageBonus")
                                .HasColumnType("double precision");

                            b1.Property<double>("ElementalResistance")
                                .HasColumnType("double precision");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerItemId");

                            b1.ToTable("PlayerItems");

                            b1.WithOwner()
                                .HasForeignKey("PlayerItemId");
                        });

                    b.Navigation("BonusStats")
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.DungeonAchievementDefinition", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Dungeon", "Dungeon")
                        .WithMany()
                        .HasForeignKey("DungeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dungeon");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.ExpeditionAchievementDefinition", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerDungeonAchievement", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Progress.DungeonAchievementDefinition", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Players.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerDungeonProgress", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Dungeon", "Dungeon")
                        .WithMany()
                        .HasForeignKey("DungeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Players.PlayerProfile", "Player")
                        .WithMany("DungeonProgress")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dungeon");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerExpeditionAchievement", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Progress.ExpeditionAchievementDefinition", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Players.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Progress.PlayerExpeditionProgress", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Players.PlayerProfile", "Player")
                        .WithMany("ExpeditionProgress")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.MercenaryTemplate", b =>
                {
                    b.OwnsOne("MercenariesAndBeasts.Domain.Combat.StatBlock", "BaseStats", b1 =>
                        {
                            b1.Property<Guid>("MercenaryTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer");

                            b1.Property<double>("CritChance")
                                .HasColumnType("double precision");

                            b1.Property<double>("CritMultiplier")
                                .HasColumnType("double precision");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("ElementalDamageBonus")
                                .HasColumnType("double precision");

                            b1.Property<double>("ElementalResistance")
                                .HasColumnType("double precision");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.HasKey("MercenaryTemplateId");

                            b1.ToTable("MercenaryTemplates");

                            b1.WithOwner()
                                .HasForeignKey("MercenaryTemplateId");
                        });

                    b.Navigation("BaseStats")
                        .IsRequired();
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.MonsterTemplate", b =>
                {
                    b.OwnsOne("MercenariesAndBeasts.Domain.Combat.StatBlock", "BaseStats", b1 =>
                        {
                            b1.Property<Guid>("MonsterTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer");

                            b1.Property<double>("CritChance")
                                .HasColumnType("double precision");

                            b1.Property<double>("CritMultiplier")
                                .HasColumnType("double precision");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("ElementalDamageBonus")
                                .HasColumnType("double precision");

                            b1.Property<double>("ElementalResistance")
                                .HasColumnType("double precision");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.HasKey("MonsterTemplateId");

                            b1.ToTable("MonsterTemplates");

                            b1.WithOwner()
                                .HasForeignKey("MonsterTemplateId");
                        });

                    b.Navigation("BaseStats")
                        .IsRequired();
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.PlayerMercenary", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Players.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Units.MercenaryTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MercenariesAndBeasts.Domain.Combat.StatBlock", "BonusStats", b1 =>
                        {
                            b1.Property<Guid>("PlayerMercenaryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer");

                            b1.Property<double>("CritChance")
                                .HasColumnType("double precision");

                            b1.Property<double>("CritMultiplier")
                                .HasColumnType("double precision");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("ElementalDamageBonus")
                                .HasColumnType("double precision");

                            b1.Property<double>("ElementalResistance")
                                .HasColumnType("double precision");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerMercenaryId");

                            b1.ToTable("PlayerMercenaries");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMercenaryId");
                        });

                    b.Navigation("BonusStats")
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Units.PlayerMonster", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Players.PlayerProfile", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Domain.Units.MonsterTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MercenariesAndBeasts.Domain.Combat.StatBlock", "BonusStats", b1 =>
                        {
                            b1.Property<Guid>("PlayerMonsterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer");

                            b1.Property<double>("CritChance")
                                .HasColumnType("double precision");

                            b1.Property<double>("CritMultiplier")
                                .HasColumnType("double precision");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer");

                            b1.Property<string>("Element")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("ElementalDamageBonus")
                                .HasColumnType("double precision");

                            b1.Property<double>("ElementalResistance")
                                .HasColumnType("double precision");

                            b1.Property<int>("MaxHp")
                                .HasColumnType("integer");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer");

                            b1.HasKey("PlayerMonsterId");

                            b1.ToTable("PlayerMonsters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerMonsterId");
                        });

                    b.Navigation("BonusStats")
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Items.ItemEffect", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Domain.Items.ItemTemplate", null)
                        .WithMany("Effects")
                        .HasForeignKey("ItemTemplateId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Infrastructure.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Infrastructure.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercenariesAndBeasts.Infrastructure.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MercenariesAndBeasts.Infrastructure.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Dungeon", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Items.ItemTemplate", b =>
                {
                    b.Navigation("Effects");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Location", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("MercenariesAndBeasts.Domain.Players.PlayerProfile", b =>
                {
                    b.Navigation("DungeonProgress");

                    b.Navigation("ExpeditionProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
