
namespace MercenariesAndBeasts.Enums{
public enum MainHandItem
{
    IronBlade,
    SteelSaber,
    WarAxe,
    TwinDagger,
    BattleSpear,
    Runeblade,
    EmberEdge,
    Frostbrand,
    StormSlicer,
    AetherBlade,
    CelestialGreatsword
}
public enum OffHandItem
{
    WoodenShield,
    IronShield,
    SteelBuckler,
    ParryingDagger,
    MysticCharm,
    WardTome,
    EmberFocus,
    FrostFocus,
    StormOrb,
    AetherSigil,
    CelestialBulwark
}
public enum HeadgearItem
{
    LeatherCap,
    IronHelm,
    SteelHelm,
    ScoutMask,
    BattleVisor,
    RuneHelm,
    EmberCrown,
    FrostHelm,
    StormHelm,
    AetherCowl,
    CelestialHelm
}
public enum ChestguardItem
{
    LeatherArmor,
    IronChestplate,
    SteelArmor,
    ScoutVest,
    BattlePlate,
    RuneArmor,
    EmberPlate,
    FrostMail,
    StormArmor,
    AetherRobes,
    CelestialArmor
}
public enum LegwearItem
{
    LeatherLegs,
    IronGreaves,
    SteelGreaves,
    ScoutPants,
    BattleLegs,
    RuneLeggings,
    EmberGreaves,
    FrostLegs,
    StormLegs,
    AetherTreads,
    CelestialLegguards
}
public enum FootgearItem
{
    LeatherBoots,
    IronBoots,
    SteelBoots,
    ScoutBoots,
    BattleBoots,
    RuneBoots,
    EmberBoots,
    FrostBoots,
    StormBoots,
    AetherWalkers,
    CelestialStride
}
public enum ShoulderItem
{
    LeatherPads,
    IronPauldrons,
    SteelPauldrons,
    ScoutMantle,
    BattleShoulders,
    RunePauldrons,
    EmberShoulders,
    FrostMantle,
    StormFlare,
    AetherMantle,
    CelestialPauldrons
}
public enum BackItem
{
    TravelCloak,
    LeatherCape,
    ScoutCloak,
    RangerCape,
    BattleCloak,
    RuneCape,
    EmberCape,
    FrostCape,
    StormCape,
    AetherShroud,
    CelestialWings
}
public enum BeltItem
{
    LeatherBelt,
    IronBelt,
    SteelBelt,
    ScoutBelt,
    BattleBelt,
    RuneBelt,
    EmberSash,
    FrostSash,
    StormBelt,
    AetherChain,
    CelestialGirdle
}
public enum TrinketItem
{
    WoodenCharm,
    CopperTalisman,
    SilverCharm,
    RuneShard,
    SpiritBead,
    EmberTalisman,
    FrostGem,
    StormAmulet,
    AetherPendant,
    CelestialOrb,
    PrimordialSigil
}
public enum RelicItem
{
    AncientCoin,
    ForgottenIdol,
    RuneTablet,
    SpiritRelic,
    FlameRelic,
    FrostRelic,
    StormRelic,
    AetherRelic,
    CelestialRelic,
    PrimordialRelic,
    AscendantRelic
}

public enum FangItem
{
    BoneFang,
    IronFang,
    VenomFang,
    EmberFang,
    FrostFang,
    StormFang,
    VoidFang,
    AetherFang,
    PrimalFang,
    CelestialFang,
    AscendantFang
}
public enum ClawItem
{
    BoneClaw,
    IronClaw,
    SerratedClaw,
    EmberClaw,
    FrostClaw,
    StormClaw,
    VoidClaw,
    AetherClaw,
    PrimalClaw,
    CelestialClaw,
    AscendantClaw
}
public enum SkullItem
{
    BoneCrest,
    HornedSkull,
    CarvedSkull,
    EmberSkull,
    FrostSkull,
    StormSkull,
    VoidSkull,
    AetherCrest,
    PrimalSkull,
    CelestialCrest,
    AscendantSkull
}
public enum CarapaceItem
{
    BoneShell,
    ChitinShell,
    IronCarapace,
    EmberCarapace,
    FrostCarapace,
    StormCarapace,
    VoidCarapace,
    AetherCarapace,
    PrimalCarapace,
    CelestialCarapace,
    AscendantCarapace
}
public enum HindLegItem
{
    BoneStrider,
    ChitinStrider,
    IronStride,
    EmberStride,
    FrostStride,
    StormStride,
    VoidStride,
    AetherStride,
    PrimalStride,
    CelestialStride,
    AscendantStride
}
public enum TalonItem
{
    BoneTalon,
    SteelTalon,
    VenomTalon,
    EmberTalon,
    FrostTalon,
    StormTalon,
    VoidTalon,
    AetherTalon,
    PrimalTalon,
    CelestialTalon,
    AscendantTalon
}
public enum SpineItem
{
    BoneSpine,
    ChitinSpine,
    RazorSpine,
    EmberSpine,
    FrostSpine,
    StormSpine,
    VoidSpine,
    AetherSpine,
    PrimalSpine,
    CelestialSpine,
    AscendantSpine
}
public enum DorsalItem
{
    BoneRidge,
    ChitinRidge,
    IronDorsal,
    EmberDorsal,
    FrostDorsal,
    StormDorsal,
    VoidDorsal,
    AetherDorsal,
    PrimalDorsal,
    CelestialDorsal,
    AscendantDorsal
}
public enum GirthItem
{
    BoneGirth,
    ChitinGirth,
    IronGirth,
    EmberGirth,
    FrostGirth,
    StormGirth,
    VoidGirth,
    AetherGirth,
    PrimalGirth,
    CelestialGirth,
    AscendantGirth
}
public enum EssenceItem
{
    SpiritEssence,
    EmberEssence,
    FrostEssence,
    StormEssence,
    VoidEssence,
    AetherEssence,
    PrimalEssence,
    CelestialEssence,
    AstralEssence,
    MythicEssence,
    AscendantEssence
}
public enum CoreItem
{
    BoneCore,
    EmberCore,
    FrostCore,
    StormCore,
    VoidCore,
    AetherCore,
    PrimalCore,
    CelestialCore,
    AstralCore,
    MythicCore,
    AscendantCore
}
}